version: 2.1
orbs:
  # declaring the orbs for setting up the servers and softwares during the CI/CD process.
  # node js, aws and eb is going to be used.
  node: circleci/node@5.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    # setting up all the softwares used for installation, building and deploying the application.
    steps:
      - node/install
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version